- hosts: localhost
  become: true
  pre_tasks:
     - set_fact:
          playbook_dir: /home/projects/kieran/ansible-projects/workstation
#    - name: bootstrap ansible dependancies
#      raw: dnf -y -e0 -d0 install python3-dnf
#    - name: update repositories
#      dnf: update_cache=yes
#      changed_when: False
#    - name: upgrade all current packages
#      dnf:
#        name: "*"
#        state: latest

  tasks:
#    - include: tasks/debug.yml
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/cron.yml
