- name: Remove outdated docker builds
  dnf:
    name: [
          'docker',
          'docker-client',
          'docker-client-latest',
          'docker-common',
          'docker-latest',
          'docker-latest-logrotate',
          'docker-logrotate',
          'docker-selinux',
          'docker-engine-selinux',
          'docker-engine'
          ]
    state: absent

- name: Install dnf-plugins
  dnf:
    name: dnf-plugins-core
    state: present

- name: Check for docker-ce repo
  shell: dnf repolist --enabled | grep docker-ce-stable
  ignore_errors: yes
  args:
    warn: no
  register: docker_repo_enabled
  changed_when: false

- name: Add docker-ce repo
  shell: dnf config-manager \
          --add-repo \
          https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    warn: no
  when: docker_repo_enabled.rc != 0

- name: Install docker
  dnf:
    name: 'docker-ce'
    state: latest

- name: Start docker service and enable on boot
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Create docker group
  group:
    name: docker

- name: Add user to docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
# Force reload of some kind for group change to take effect
