#- name: Gather facts for rvm
#  setup:
#   - set_fact:
#        rvm_galaxy: /etc/ansible
#        user: kieran

- name: Install ansible-galaxy rvm role
  shell: ansible-galaxy install rvm.ruby
  when: '"/etc/ansible/roles/rvm.ruby" is not directory'

#- include_role:
#     name: foo_app_instance
#  vars:
#    dir: '/opt/a'
#    app_port: 5000
