- name: Install ansible-galaxy rvm role
  shell: ansible-galaxy install rvm.ruby
  when: '"/etc/ansible/roles/rvm.ruby" is not directory'

- name: Set defaults for rvm role
  copy:
    src: files/rvm_role_defaults.yml
    dest: /etc/ansible/roles/rvm.ruby/defaults/main.yml

# Add compatibility for other shells later
- name: rvm as a function to .bashrc
  lineinfile:
    path: "/home/{{ user }}/.bashrc"
    line: '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"'
    create: yes

- include_role:
     name: rvm.ruby

- name: rvm cleanup
  shell: source $HOME/.rvm/scripts/rvm && rvm cleanup all
  args:
    executable: /bin/bash
  become: yes
  become_user: "{{ user }}"
  changed_when: false
