- name: Install ansible-galaxy rvm role
  shell: ansible-galaxy install rvm.ruby
  when: '"/etc/ansible/roles/rvm.ruby" is not directory'

- name: Set defaults for rvm role
  copy:
    src: files/rvm_role_defaults.yml
    dest: /etc/ansible/roles/rvm.ruby/defaults/main.yml

- include_role:
     name: rvm.ruby

- name: rvm cleanup
  shell: rvm cleanup all
  become: yes
  become_user: "{{ user }}"
  changed_when: false
