FROM debian:buster-slim

# Install required packaged
RUN apt-get update && apt-get install -y \
      sudo \
      passwd \
      wget \
      tar \
      python2 \
      python-setuptools

RUN wget https://releases.ansible.com/ansible/ansible-latest.tar.gz \
    && tar --directory=/ -xzvf ansible-latest.tar.gz \
    && rm ansible-latest.tar.gz \
    && cd /ansible-* \
    && python setup.py install

#      software-properties-common \
#      gpg \
#    && apt-add-repository ppa:ansible/ansible \
#    && apt-get update \
#    && apt-get install -y \
#      ansible

# Add user
ARG HOST_USER_ID
ARG HOST_USER_GID
RUN groupadd -r -g $HOST_USER_GID kieran && useradd -r -u $HOST_USER_ID -g kieran -G sudo,audio,video kieran \
    && mkdir -p /home/kieran/projects && chown -R kieran:kieran /home/kieran \
    && echo 'kieran:1' | chpasswd
#    && echo 1 | passwd kieran --stdin

# Packages that will be installed by ansible anyway
#RUN apt-get install -y \
#      libselinux \
#      htop \
#      nano \
#      gedit \
#      gedit-plugins \
#      git

# Run as user
USER kieran

WORKDIR /home/kieran/projects/ansible-projects/workstation

ENTRYPOINT ["tail", "/dev/null", "-f"]
