FROM debian:stretch-slim

# Install required packaged
RUN apt-get update && apt-get install -y \
      sudo \
      passwd \
      ansible

# Add user
ARG HOST_USER_ID
ARG HOST_USER_GID
RUN groupadd -r -g $HOST_USER_GID kieran && useradd -r -u $HOST_USER_ID -g kieran -G sudo,audio,video kieran \
    && mkdir -p /home/kieran/projects && chown -R kieran:kieran /home/kieran \
    && echo 'kieran:1' | chpasswd
#    && echo 1 | passwd kieran --stdin

# Packages that will be installed by ansible anyway
#RUN apt-get install -y \
#      libselinux \
#      htop \
#      nano \
#      gedit \
#      gedit-plugins \
#      git

# Run as user
USER kieran

WORKDIR /home/kieran/projects/ansible-projects/workstation

ENTRYPOINT ["tail", "/dev/null", "-f"]
