FROM fedora:28

# Install required packaged
RUN dnf install -y \
      sudo \
      passwd \
      ansible \
    && rm -rf /var/lib/apt/lists/*

# Add user
ARG HOST_USER_ID
ARG HOST_USER_GID
RUN groupadd -r -g $HOST_USER_GID kieran && useradd -r -u $HOST_USER_ID -g kieran -G wheel,audio,video kieran \
    && mkdir -p /home/kieran/projects && chown -R kieran:kieran /home/kieran \
    && echo 1 | passwd kieran --stdin

# Packages that will be installed by ansible anyway
RUN dnf install -y \
      libselinux \
      htop \
      nano \
      gedit \
      gedit-plugins \
      git

# Run as user
USER kieran

WORKDIR /home/kieran/projects/ansible-projects/workstation

ENTRYPOINT ["tail", "/dev/null", "-f"]
