- debug:
    msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"

#- debug:
#    msg: "{{ user }}"

- debug:
    msg: "{{ playbook_dir }}"

- shell: /usr/bin/whoami
  register: result

- shell: /usr/bin/whoami
  register: result
  become_user: kieran

- name: test2
  shell: echo f
  when: "playbook_dir | regex_search('(kieran)')"
