- name: create ansible group
  group:
    name: ansible
    gid: 900

- name: create ansible user
  user:
    name: ansible
    group: ansible
    uid: 900

# Sort out proper permissions later
- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440
